class test:
     def m1(self):
        def calculator(a,b):
            print(" the sum is ",a + b)
            print(" the sub is ",a - b)
            print(" the mul is ",a * b)
            print(" the div is ",a / b)
            print()   

            calculator(10,20)
            calculator(100,200)
            calculator(10000,2000)


t= test()
t.m1()

















# class test:
#     def m1(self):
#         a,b = 10, 20
#         print(" the sum is ",a + b)
#         print(" the sub is ",a - b)
#         print(" the mul is ",a * b)
#         print(" the div is ",a / b)
#         print()

#         a,b = 100, 200
#         print(" the sum is ",a + b)
#         print(" the sub is ",a - b)
#         print(" the mul is ",a * b)
#         print(" the div is ",a / b)
#         print()


#         a,b = 1000, 2000
#         print(" the sum is ",a + b)
#         print(" the sub is ",a - b)
#         print(" the mul is ",a * b)
#         print(" the div is ",a / b)
#         print()

# o = test()
# o.m1()        