#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<pthread.h>
#include<wait.h>


// HOW TO RUN
//sudo gcc -lpthread -o Fabonnachi Fabonnachi.c

struct share{
	int n;
	int copydata[];
};


void* printFabonachi(void* s){
	sleep(5);
	struct share *struct_share = s;
	
	//print the data	
	int size = struct_share->n * sizeof(struct_share->copydata[0]) / sizeof(int);
	//print the data	
	printf("1 ");
	for(int i=0; i < size; i++){
	printf("%d ",struct_share->copydata[i]);
	}
	printf("\n");
		
}

void* genFabonachi(void* s){
		
	struct share *struct_share = s;
	
	// GENERATING THE FABONACHI SERIES FROM USER GIVEN VALUES	
	int a=0,b=1,c,temp;
	int* data =  (int*)malloc(sizeof(struct_share->n));
	a=0;
	b=1;
	printf("1 ");
	for(int i=0; i < struct_share->n  ; i++){
	c = a+b;
	temp = c + b;
	printf("%d ",c);	
	data[i]=c;
	a=c;
	b=temp;
	}
	printf("\n");
	
	//copy data so that it can be shared in the other thread
	int size = struct_share->n * sizeof(*data) / sizeof(int);
	for(int i=0; i < size; i++){
		struct_share->copydata[i]=data[i];
	}
	printf("\n");
	
}

int main(){
	
	struct share s;
	struct share* copydata = malloc(sizeof(struct share) + 200);

	// GENERATING THE FABONACHI SERIES FROM USER GIVEN VALUES	
	printf("Please enter the number till which you want to print fabonachi series\n");
	scanf("%d",&s.n);
	
	// creating parent and child thread
	pthread_t th1;
	pthread_t th2;
	pthread_create(&th1,NULL,genFabonachi,&s);
	pthread_create(&th2,NULL,printFabonachi,&s);
	
	printf("CHILD THREAD IS GENERATING THE FABONACHI SERIES...\n");
	pthread_join(th1,NULL);
	
	wait(NULL);

	printf("PARENT THREAD IS PRINTING THE FABONACHI SERIES GENERATED BY THE CHILD...\n");
	pthread_join(th2,NULL);
	
	pthread_exit(0);
}